=== japotrad/blue-sky/documents/furigana.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT furigana (furi*)>
<!ATTLIST furigana xmlns CDATA #FIXED "https://github.com/japotrad/blue-sora/furigana">
<!ATTLIST furigana xml:lang CDATA #FIXED "ja" >
<!ELEMENT furi EMPTY>
<!-- The location is the id of the segment where the furigana is located (e.g., p2).
     A space-separated list can be used (e.g. p1 p3).
     If there is no location, it means that the furigana is potentially located on all segments.
 -->
<!ATTLIST furi location CDATA #IMPLIED>
<!-- Kanji is typically composed of Chinese characters. -->
<!ATTLIST furi kanji CDATA #REQUIRED>
<!-- Kana is typically composed of (phonetically transparent) hiragana characters. -->
<!ATTLIST furi kana CDATA #REQUIRED>

=== japotrad/blue-sky/documents/4402-furigana.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE furigana
  SYSTEM "furigana.dtd">
<furigana>
   <furi location="p1" kanji="駄洒落" kana="だじゃれ"/>
   <furi location="p1" kanji="笑" kana="わらい"/>
   <furi location="p1" kanji="陰鬱" kana="いんうつ"/>
   <furi location="p1" kanji="朗" kana="ほがら"/>
   <furi location="p1" kanji="双児" kana="ふたご"/>
   <furi location="p1" kanji="譬" kana="たと"/>
   <furi location="p1" kanji="咎" kana="とが"/>
   <furi location="p2" kanji="西田幾多郎" kana="にしだきたろう"/>
   <furi location="p2" kanji="貴船" kana="きぶね"/>
   <furi location="p3" kanji="貰" kana="もら"/>
</furigana>
