=== japotrad/blue-sky/documents/ris.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!-- Extract of a single RIS bibliographic record --> 
<!ELEMENT ris (TI|A4|AB|AU|PY|UR)*>
<!ATTLIST ris xmlns CDATA #FIXED "https://github.com/japotrad/blue-sora/ris">
 <!-- Document title -->
<!ELEMENT TI (#PCDATA)>
<!-- Original author name -->
<!ELEMENT AU (#PCDATA|LAST|FIRST)*>
<!-- Translator name -->
<!ELEMENT A4 (#PCDATA|LAST|FIRST)*>
<!-- Last name -->
<!ELEMENT LAST (#PCDATA)>
<!-- First name -->
<!ELEMENT FIRST (#PCDATA)>
<!-- Abstract -->
<!ELEMENT AB (#PCDATA)>
<!-- Publication year -->
<!ELEMENT PY (#PCDATA)>
<!-- URL of the Aozora Bunko card -->
<!ELEMENT UR (#PCDATA)>

=== japotrad/blue-sky/documents/4402-fr-ris.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ris SYSTEM "ris.dtd">
<ris xmlns="https://github.com/japotrad/blue-sora/ris">
  <TI>Calembours fortuits</TI>
  <AU><LAST>Kuki</LAST><FIRST>Shūzō</FIRST></AU>
  <A4>Japotrad</A4>
  <AB>Que ce soit à Paris en français dans les années 1920 ou à Kyoto en japonais dans les années 1930, les jeux de mots que Kuki rencontre par hasard dans sa vie personnelle viennent nourrir sa réflexion et égayer son quotidien.</AB>
  <PY>2024</PY>
  <UR>https://www.aozora.gr.jp/cards/000065/card4402.html</UR>
</ris>
